# Generated by Django 3.2.6 on 2021-08-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_state_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(editable=False, max_length=255, verbose_name='Nome do Estado'),
        ),
    ]
